name: PR to master notification

on:
  pull_request:
    branches: [ master ]

jobs:
  message-to-slack-about-pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: message to slack
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":" ${{ github.actor }} made a pr to master"}' https://hooks.slack.com/services/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
