name: PR to master notification

on:
  pull_request:
    branches: [ development ]

jobs:
  message-to-slack-about-pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: message to slack
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"backend: ${{ github.actor }} made a pr to development"}' https://hooks.slack.com/services/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
