# This is a basic workflow to help you get started with Actions

name: selfhosted runner

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-run:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          mvn clean install
          npx kill-port 8080
          npx kill-port 8080
          npx kill-port 8080
          cd target
          dir
          "java -jar gloryautofab-0.0.1-SNAPSHOT.jar > log.txt 2> 1 &"
